"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, ArrowDownLeft, CircleDollarSign, Layers3, MessageCircle, Plus, RefreshCw, Wallet } from "lucide-react";
import type { Overview, CompanyCard, ChannelStatus, Suggestion } from "@contracts/types";
import { cancelOrder, getChannel, getOverview, listCompanies, suggestPortfolio } from "@/lib/api";
import { usd, signed } from "@/lib/format";
import { Button } from "@/components/ui/button";
import { BusinessAvatar, EmptyState, MarketCard, Neighborhood, OrdersTable } from "./shared";
import { Suggestions } from "@/components/portfolio/suggestions";

export function OverviewDashboard({portfolioOnly=false}:{portfolioOnly?:boolean}) {
 const [data,setData]=useState<Overview|null>(null),[companies,setCompanies]=useState<CompanyCard[]>([]),[channel,setChannel]=useState<ChannelStatus|null>(null),[suggestions,setSuggestions]=useState<Suggestion[]>([]);
 const [error,setError]=useState(""),[busy,setBusy]=useState<string|null>(null),[filter,setFilter]=useState("active"),[refreshing,setRefreshing]=useState(false);
 const refresh=useCallback(async()=>{const [account,messaging]=await Promise.allSettled([getOverview(),getChannel()]);if(account.status==="fulfilled"){setData(account.value);setError("");}else{setError(account.reason instanceof Error?account.reason.message:"Unable to load your account");}if(messaging.status==="fulfilled")setChannel(messaging.value);},[]);
 useEffect(()=>{let alive=true;const start=async()=>{const [,cs,sg]=await Promise.allSettled([refresh(),listCompanies(),portfolioOnly?suggestPortfolio():Promise.resolve([])]);if(!alive)return;if(cs.status==="fulfilled")setCompanies(cs.value);if(sg.status==="fulfilled")setSuggestions(sg.value);};void start();const timer=setInterval(()=>void refresh(),10000);return()=>{alive=false;clearInterval(timer);};},[refresh,portfolioOnly]);
 const cancel=async(id:string)=>{setBusy(id);try{await cancelOrder(id);await refresh();}catch(e){setError(e instanceof Error?e.message:"Cancellation failed");}finally{setBusy(null);}};
 const holdings=data?.portfolio.positions.reduce((s,p)=>s+p.value,0)??0;
 const cash=data?.portfolio.cash??0;
 const equity=holdings+cash;
 const pnl=data?.portfolio.pnl.total??0;
 const rows=data?.orders.filter(o=>filter==="all"|| (filter==="active"?(o.status==="open"||o.status==="partial"):o.status==="filled"))??[];
 const featured=companies.filter(c=>c.status==="ready"&&c.state==="PA").sort((a,b)=>(b.confidence??0)-(a.confidence??0)).slice(0,4);
 const date=new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date());
 return <div className="page-wrap fade-up">
   <div className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><div className="eyebrow mb-2">Your corner of the market</div><h1 className="page-title">{portfolioOnly?"Your portfolio.":"A world of opportunity."}</h1><p className="page-subtitle">{portfolioOnly?"Every stake. Every move. All in one place.":"Small businesses. Real potential. Make your next move."}</p></div><div className="flex items-center gap-3"><span className="hidden lg:inline text-xs secondary">{date}</span><button onClick={async()=>{setRefreshing(true);await refresh();setRefreshing(false);}} aria-label="Refresh overview" className="rounded-lg border border-line bg-white p-2.5 text-muted-foreground"><RefreshCw size={14} className={refreshing?"animate-spin":""}/></button><Button href="/search" variant="primary"><Plus size={14}/>Explore businesses</Button></div></div>
   {data&&data.orders.length>0&&<div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-line bg-white px-5 py-3"><span className="flex items-center gap-2 text-xs secondary"><MessageCircle size={16} className={channel?.connected?"text-up":"text-muted-foreground"}/>{channel?.connected?"iMessage bridge connected":channel?.configured?"iMessage bridge offline":"iMessage is not connected"}<span className="hidden md:inline">· Updated {new Date(data.as_of).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></span><Link href="/agent" className="flex items-center gap-2 text-xs text-accent">Open your conversation<ArrowRight size={13}/></Link></div>}
   {error&&<div role="alert" className="mb-5 rounded-lg border border-down/20 bg-down/5 p-3 text-sm text-down">{error} <button onClick={()=>void refresh()} className="ml-2 underline">Retry</button></div>}
   <div className="mb-6 grid grid-cols-2 gap-3 xl:grid-cols-4 xl:gap-5">{[
     {label:"Total account value",value:equity,icon:Wallet,detail:`${data?.portfolio.positions.length??0} businesses in your portfolio`,color:"#7761c6"},
     {label:"Available to invest",value:Math.max(0,cash-(data?.reserved_cash??0)),icon:CircleDollarSign,detail:data?.reserved_cash?`${usd(data.reserved_cash)} in open bids`:"Ready for your next opportunity",color:"#5c9d87"},
     {label:"Active orders",value:data?.open_orders??0,icon:Layers3,detail:`${data?.orders.filter(o=>o.status==="filled").length??0} completed orders`,color:"#b68b63",count:true},
     {label:"Total return",value:pnl,icon:ArrowUpRight,detail:"Realized + unrealized",color:"#788db1",signed:true},
   ].map(m=><div key={m.label} className="dashboard-panel metric-card"><div className="mb-4 flex items-center justify-between"><span className="text-[11px] text-muted-foreground">{m.label}</span><m.icon size={16} strokeWidth={1.5} style={{color:m.color}}/></div><div className={`metric-value ${m.signed&&m.value>0?"text-up":m.signed&&m.value<0?"text-down":""}`}>{!data?"—":m.count?m.value:m.signed?`${m.value>0?"+":m.value<0?"−":""}${usd(Math.abs(m.value))}`:usd(m.value)}</div><p className="mt-2 text-[10px] text-muted-foreground">{m.detail}</p></div>)}</div>
   {!portfolioOnly&&(!data||data.orders.length===0)&&<div className="mb-7 grid gap-5 xl:grid-cols-[1.9fr_1fr]"><section className="hero-discover"><div className="relative z-10 max-w-[64%]"><span className="eyebrow text-[#655877]">The next big thing is local</span><h2 className="mt-4 text-[30px] leading-[1.1] tracking-[-.045em]">Own a little.<br/>Dream a lot.</h2><p className="mt-3 max-w-[250px] text-xs leading-5 text-[#655877]">Find the businesses you believe in.<br/>Start with a stake. Make it your own.</p><Link href="/search" className="mt-5 inline-flex items-center gap-6 rounded-lg bg-white px-4 py-2.5 text-xs text-[#625077]">Find your opportunity<ArrowUpRight size={14}/></Link></div><Neighborhood/></section><section className="dashboard-panel flex flex-col p-6"><div className="flex items-start justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-up/10 text-up"><MessageCircle size={22} strokeWidth={1.5}/></span><span className={`soft-tag ${channel?.connected?"!bg-up/10 !text-up":"!bg-surface !text-muted-foreground"}`}><span className="status-dot"/>{channel?.connected?"Connected":channel?.configured?"Awaiting bridge":"Not connected"}</span></div><h2 className="mt-5 text-lg">Your next move.<br/>Just a message away.</h2><p className="mt-2 text-xs leading-5 secondary">Find businesses and follow your orders with Bartr on iMessage.</p><div className="mt-auto pt-4"><Link href="/agent" className="flex items-center justify-between text-xs text-accent">Open your assistant<ArrowRight size={14}/></Link></div></section></div>}
   <div className="mb-7 grid items-start gap-5 xl:grid-cols-[1.9fr_1fr]"><section className="dashboard-panel"><div className="flex flex-wrap items-center justify-between gap-3 px-5 py-4"><h2 className="section-title">Your orders <span className="ml-2 text-xs text-muted-foreground">{data?.orders.length??0}</span></h2><div className="flex gap-1 rounded-lg bg-surface p-1" role="group" aria-label="Filter orders">{[["active","Active"],["filled","Filled"],["all","All orders"]].map(([v,l])=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)} className={`rounded-md px-2.5 py-1.5 text-[10px] ${filter===v?"bg-white text-foreground":"text-muted-foreground"}`}>{l}</button>)}</div></div>{!data?<div className="h-40 animate-pulse bg-surface/50"/>:rows.length?<OrdersTable orders={rows} cancel={cancel} busy={busy}/>:<EmptyState title={filter==="active"?"Your next move starts here":"No orders in this view"} description={filter==="active"?"Choose a business, set your price, and follow your order here.":"Your completed and cancelled orders stay in your history."} href="/search" label="Find a business to invest in"/>}</section><section className="dashboard-panel p-5"><div className="flex items-center justify-between"><h2 className="section-title">Your allocation</h2><Link href="/portfolio" aria-label="View portfolio" className="text-muted-foreground hover:text-accent"><ArrowUpRight size={16}/></Link></div><div className="flex items-center gap-6 py-6"><div className="relative size-[110px] shrink-0"><svg viewBox="0 0 120 120" className="size-full -rotate-90" role="img" aria-label={`${equity?Math.round(holdings/equity*100):0}% invested; remainder in cash`}><circle cx="60" cy="60" r="49" fill="none" stroke="#eeebf8" strokeWidth="12"/><circle cx="60" cy="60" r="49" fill="none" stroke="#8873d0" strokeWidth="12" strokeDasharray={`${equity?holdings/equity*308:0} 308`} strokeLinecap="round"/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-xl tracking-tight">{equity?Math.round(holdings/equity*100):0}%</span><span className="text-[9px] secondary">invested</span></div></div><div className="flex-1 space-y-5">{[["Business stakes",holdings,"#8873d0"],["Cash balance",cash,"#dcd7ed"]].map(([l,v,c])=><div key={String(l)}><p className="flex items-center gap-2 text-[10px] secondary"><span className="size-1.5 rounded-full" style={{background:String(c)}}/>{l}</p><p className="mt-1 text-sm tabular-nums">{data?usd(Number(v)):"—"}</p></div>)}</div></div><div className="border-t border-hairline pt-3 text-[10px] secondary">{data?.portfolio.positions.length??0} businesses · {data?.open_orders??0} active orders</div></section></div>
   {portfolioOnly&&<section className="dashboard-panel mb-7"><div className="px-5 py-4"><h2 className="section-title">Your holdings</h2></div>{data?.portfolio.positions.length?<div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Business</th><th>Shares</th><th>Average cost</th><th>Market value</th><th>Return</th></tr></thead><tbody>{data.portfolio.positions.map(p=><tr key={p.market_id}><td><Link href={`/company/${p.market_id}`} className="flex items-center gap-3"><BusinessAvatar category={companies.find(c=>c._id===p.market_id)?.category??"business"}/>{p.name}</Link></td><td className="font-mono">{p.qty}</td><td className="font-mono">{usd(p.avg_cost)}</td><td className="font-mono">{usd(p.value)}</td><td className={`font-mono ${p.pnl>=0?"text-up":"text-down"}`}>{signed(p.pnl)}</td></tr>)}</tbody></table></div>:<EmptyState title="Build a portfolio you believe in" description="Your investments will appear here as your orders fill." href="/search"/>}</section>}
   {portfolioOnly&&<section className="dashboard-panel mb-7 p-6">{suggestions.length?<Suggestions initial={suggestions} bankroll={Math.max(0,cash-(data?.reserved_cash??0))}/>:<EmptyState title="No suggested stakes right now" description="Explore the market or ask your assistant to help find a business." href="/agent" label="Ask Bartr"/>}</section>}
   {!portfolioOnly&&<section><div className="mb-4 flex items-end justify-between"><div><h2 className="section-title">Around the neighborhood</h2><p className="mt-1 text-xs secondary">A few businesses worth a closer look.</p></div><Link href="/search" className="flex items-center gap-2 text-xs text-accent">Explore all<ArrowRight size={13}/></Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{featured.map(c=><MarketCard key={c._id} company={c}/>)}</div>{!featured.length&&<div className="dashboard-panel"><EmptyState title="Find your neighborhood" description="Search a city and the kind of business you have in mind." href="/search"/></div>}</section>}
   {data&&data.activity.length>0&&<section className="dashboard-panel mt-7"><div className="border-b border-hairline px-5 py-4"><h2 className="section-title">Recent activity</h2></div><div className="divide-y divide-hairline">{data.activity.slice(0,5).map((a,i)=><div key={a.id??i} className="flex items-center gap-3 px-5 py-3"><ArrowDownLeft size={15} className="text-accent"/><span className="flex-1 text-xs">{a.action.replaceAll("_"," ")}</span><span className="text-[10px] secondary">{new Date(a.t).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div>)}</div></section>}
 </div>;
}
