/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/discovery/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Search */
        post: operations["start_search_api_v1_discovery_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discovery/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Stream */
        get: operations["job_stream_api_v1_discovery_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_v1_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_v1_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Company */
        post: operations["refresh_company_api_v1_companies__company_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/{market_id}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book */
        get: operations["get_book_api_v1_markets__market_id__book_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/{market_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Place Order */
        post: operations["place_order_api_v1_markets__market_id__orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Order */
        delete: operations["cancel_order_api_v1_orders__order_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/{market_id}/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_api_v1_markets__market_id__batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/{market_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trades */
        get: operations["list_trades_api_v1_markets__market_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_api_v1_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Profile */
        put: operations["put_profile_api_v1_portfolio_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest */
        post: operations["suggest_api_v1_portfolio_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acquire/{company_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_v1_acquire__company_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acquire/{acquisition_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_acquire__acquisition_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/surveillance/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flags */
        get: operations["flags_api_v1_surveillance_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/surveillance/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_v1_surveillance_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description What is actually wired up. Useful during key collection.
         */
        get: operations["readiness_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcquisitionStart */
        AcquisitionStart: {
            /** Acquisition Id */
            acquisition_id: string;
            /** Loi Md */
            loi_md: string;
            /**
             * Checklist
             * @default []
             */
            checklist: components["schemas"]["ChecklistItem"][];
        };
        /** AuditEntry */
        AuditEntry: {
            /** Id */
            id: string;
            /**
             * T
             * Format: date-time
             */
            t: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Payload Hash */
            payload_hash: string;
        };
        /** Batch */
        Batch: {
            /** Id */
            id: string;
            /** Market Id */
            market_id: string;
            /**
             * T
             * Format: date-time
             */
            t: string;
            /** Clearing Price */
            clearing_price: number;
            /** Volume */
            volume: number;
            /**
             * Imbalance
             * @default 0
             */
            imbalance: number;
            /**
             * N Buy
             * @default 0
             */
            n_buy: number;
            /**
             * N Sell
             * @default 0
             */
            n_sell: number;
        };
        /** Book */
        Book: {
            /** Market Id */
            market_id: string;
            /**
             * Bids
             * @default []
             */
            bids: components["schemas"]["BookLevel"][];
            /**
             * Asks
             * @default []
             */
            asks: components["schemas"]["BookLevel"][];
            /** Last */
            last?: number | null;
            /** Ref */
            ref?: number | null;
            /** Next Batch At */
            next_batch_at?: string | null;
            /**
             * Band
             * @default 0.1
             */
            band: number;
        };
        /** BookLevel */
        BookLevel: {
            /** Price */
            price: number;
            /** Qty */
            qty: number;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** ChecklistItem */
        ChecklistItem: {
            /** Item */
            item: string;
            /** Why */
            why?: string | null;
            source?: components["schemas"]["Source"] | null;
            /**
             * Done
             * @default false
             */
            done: boolean;
        };
        /** Company */
        Company: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** City */
            city?: string | null;
            /** State */
            state?: string | null;
            /** Rating */
            rating?: number | null;
            /** Review Count */
            review_count?: number | null;
            /** @default stub */
            status: components["schemas"]["CompanyStatus"];
            valuation?: components["schemas"]["Valuation"] | null;
            market?: components["schemas"]["MarketSummary"] | null;
            /** Address */
            address?: string | null;
            /** Website */
            website?: string | null;
            /** Phone */
            phone?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Owners
             * @default []
             */
            owners: string[];
            /** Founded Year */
            founded_year?: number | null;
            financials?: components["schemas"]["Financials"] | null;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["Source"][];
        };
        /** CompanyCard */
        CompanyCard: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** City */
            city?: string | null;
            /** State */
            state?: string | null;
            /** Rating */
            rating?: number | null;
            /** Review Count */
            review_count?: number | null;
            /** @default stub */
            status: components["schemas"]["CompanyStatus"];
            valuation?: components["schemas"]["Valuation"] | null;
            market?: components["schemas"]["MarketSummary"] | null;
        };
        /**
         * CompanyStatus
         * @enum {string}
         */
        CompanyStatus: "stub" | "ready" | "failed";
        /** Financials */
        Financials: {
            /** Revenue Est */
            revenue_est?: number | null;
            /** Sde Est */
            sde_est?: number | null;
            /** Margin Est */
            margin_est?: number | null;
            /** Employees Est */
            employees_est?: number | null;
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /**
             * Method
             * @default proxy
             */
            method: string;
        };
        /** Flag */
        Flag: {
            /** Id */
            id: string;
            /** Market Id */
            market_id: string;
            /** Batch Id */
            batch_id?: string | null;
            /** Rule */
            rule: string;
            /** Severity */
            severity: string;
            /**
             * Subjects
             * @default []
             */
            subjects: string[];
            /** Explanation */
            explanation: string;
            /** Reviewer */
            reviewer: string;
            /**
             * T
             * Format: date-time
             */
            t: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Env */
            env: string;
            /** Database */
            database: boolean;
            /** Demo Auth */
            demo_auth: boolean;
        };
        /** Intent */
        Intent: {
            /** Category */
            category?: string | null;
            /** Naics Guess */
            naics_guess?: string | null;
            /** State */
            state?: string | null;
            /** City */
            city?: string | null;
            /** Min Value */
            min_value?: number | null;
            /** Max Value */
            max_value?: number | null;
            /**
             * Must Have
             * @default []
             */
            must_have: string[];
        };
        /** MarketSummary */
        MarketSummary: {
            /** Market Id */
            market_id: string;
            /** Bid */
            bid?: number | null;
            /** Ask */
            ask?: number | null;
            /** Last */
            last?: number | null;
            /** Next Batch At */
            next_batch_at?: string | null;
            /**
             * Halted
             * @default false
             */
            halted: boolean;
        };
        /** Order */
        Order: {
            /** Id */
            id: string;
            /** Market Id */
            market_id: string;
            /** User Id */
            user_id: string;
            side: components["schemas"]["Side"];
            /** Qty */
            qty: number;
            /** Limit Price */
            limit_price: number;
            /** @default open */
            status: components["schemas"]["OrderStatus"];
            /**
             * Filled Qty
             * @default 0
             */
            filled_qty: number;
            /** @default user */
            origin: components["schemas"]["OrderOrigin"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OrderOrigin
         * @enum {string}
         */
        OrderOrigin: "user" | "mm" | "agent";
        /** OrderRequest */
        OrderRequest: {
            side: components["schemas"]["Side"];
            /** Qty */
            qty: number;
            /** Limit Price */
            limit_price: number;
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "open" | "filled" | "partial" | "cancelled";
        /** Portfolio */
        Portfolio: {
            /** Cash */
            cash: number;
            /**
             * Positions
             * @default []
             */
            positions: components["schemas"]["Position"][];
            /**
             * Pnl
             * @default 0
             */
            pnl: number;
        };
        /** Position */
        Position: {
            /** Market Id */
            market_id: string;
            /** Company Name */
            company_name?: string | null;
            /** Qty */
            qty: number;
            /** Avg Cost */
            avg_cost: number;
            /** Last */
            last?: number | null;
            /** Unrealized */
            unrealized?: number | null;
        };
        /** RiskProfile */
        RiskProfile: {
            /**
             * Tolerance
             * @default 0.5
             */
            tolerance: number;
            /**
             * Horizon
             * @default medium
             */
            horizon: string;
            /**
             * Sectors
             * @default []
             */
            sectors: string[];
            /**
             * States
             * @default []
             */
            states: string[];
            /**
             * Budget
             * @default 100000
             */
            budget: number;
        };
        /** SearchAccepted */
        SearchAccepted: {
            /** Job Id */
            job_id: string;
            intent: components["schemas"]["Intent"];
        };
        /** SearchRequest */
        SearchRequest: {
            /** Q */
            q: string;
        };
        /**
         * Side
         * @enum {string}
         */
        Side: "buy" | "sell";
        /** Source */
        Source: {
            /** Url */
            url: string;
            /** Title */
            title?: string | null;
            /** Snippet */
            snippet?: string | null;
            /** Fetched At */
            fetched_at?: string | null;
        };
        /** Suggestion */
        Suggestion: {
            company: components["schemas"]["CompanyCard"];
            /** Edge */
            edge: number;
            /** Sigma */
            sigma: number;
            /** Kelly Fraction */
            kelly_fraction: number;
            /** Suggested Usd */
            suggested_usd: number;
            /** Why */
            why: string;
        };
        /** Trade */
        Trade: {
            /** Id */
            id: string;
            /** Market Id */
            market_id: string;
            /** Batch Id */
            batch_id: string;
            /** Qty */
            qty: number;
            /** Price */
            price: number;
            /**
             * T
             * Format: date-time
             */
            t: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Cash */
            cash: number;
            /** Auth Provider */
            auth_provider: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Valuation */
        Valuation: {
            /** V0 */
            v0: number;
            /** Sigma */
            sigma: number;
            /** Low */
            low: number;
            /** High */
            high: number;
            /** Multiple Used */
            multiple_used?: number | null;
            /** As Of */
            as_of?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    start_search_api_v1_discovery_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stream_api_v1_discovery_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_api_v1_companies_get: {
        parameters: {
            query?: {
                state?: string | null;
                category?: string | null;
                q?: string | null;
                sort?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyCard"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_v1_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_company_api_v1_companies__company_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_v1_markets__market_id__book_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_order_api_v1_markets__market_id__orders_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-User"?: string | null;
            };
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_v1_orders__order_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-User"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_v1_markets__market_id__batches_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trades_api_v1_markets__market_id__trades_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trade"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_v1_portfolio_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_profile_api_v1_portfolio_profile_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_api_v1_portfolio_suggest_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_v1_acquire__company_id__start_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-User"?: string | null;
            };
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcquisitionStart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_acquire__acquisition_id__chat_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-User"?: string | null;
            };
            path: {
                acquisition_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_agent_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flags_api_v1_surveillance_flags_get: {
        parameters: {
            query?: {
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flag"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_v1_surveillance_audit_get: {
        parameters: {
            query?: {
                actor?: string | null;
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readiness_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
