"""Export GraphQL SDL without touching credentials, databases, or the REST contract.

Run with the API environment: apps/api/.venv/bin/python scripts/gen_graphql.py [--check]
"""
import argparse
import os
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps/api"))
for key in ("MONGODB_URI", "STATE_FILE", "XAI_API_KEY", "QUERIT_API_KEY", "IFM_API_KEY"):
    os.environ[key] = ""
for key in ("SEED", "BOTS", "DISCOVERY_LIVE"):
    os.environ[key] = "0"

from app.routers.graphql import schema

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
target = ROOT / "packages/contracts/schema.graphql"
rendered = "# Generated by scripts/gen_graphql.py. Do not edit by hand.\n" + schema.as_str() + "\n"
if args.check:
    if not target.exists() or target.read_text() != rendered:
        raise SystemExit("GraphQL SDL is stale; run scripts/gen_graphql.py")
else:
    target.write_text(rendered)
print("GraphQL SDL matches" if args.check else f"Exported {target.relative_to(ROOT)}")
